In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://www.isaaa.org/animalbiotechdatabase/ngtlist/ngt/default.asp?NGTID=2&RegProcess=0"
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

Total rows scraped: 153
CSV saved as 'isaa_animalbiotech_full.csv'

In [ ]:
table = soup.find('table')

rows = table.find_all('tr')

data = []

for row in rows:
    cells = row.find_all('td')
    if len(cells) < 5:
        continue
    
    country = cells[1].get_text(strip=True)
    
    # Animal: separate common and scientific names
    animal_common = cells[2].contents[0].strip() if cells[2].contents else ""
    animal_scientific = cells[2].em.get_text(strip=True) if cells[2].em else ""
    
    gene = cells[3].get_text(strip=True)
    year = cells[0].get_text(strip=True)  # first cell is year
    details_url = "https://www.isaaa.org" + cells[4].a['href'] if cells[4].a else ""
    
    data.append({
        "year": year,
        "country": country,
        "animal_common": animal_common,
        "animal_scientific": animal_scientific,
        "gene": gene,
        "details_url": details_url
    })

df = pd.DataFrame(data)
print("Total rows scraped:", len(df))
df.head()

df.to_csv("isaa_animalbiotech_full.csv", index=False)
print("CSV saved as 'isaa_animalbiotech_full.csv'")

In [ ]:
df['details_url'].head(10)

0
1    https://www.isaaa.org/animalbiotechdatabase/de...
2    https://www.isaaa.org/animalbiotechdatabase/de...
3    https://www.isaaa.org/animalbiotechdatabase/de...
4    https://www.isaaa.org/animalbiotechdatabase/de...
5    https://www.isaaa.org/animalbiotechdatabase/de...
6    https://www.isaaa.org/animalbiotechdatabase/de...
7    https://www.isaaa.org/animalbiotechdatabase/de...
8    https://www.isaaa.org/animalbiotechdatabase/de...
9    https://www.isaaa.org/animalbiotechdatabase/de...
Name: details_url, dtype: object

In [ ]:
sample_url = df.loc[df['details_url'] != "", 'details_url'].iloc[0]

sample_response = requests.get(sample_url)
sample_soup = BeautifulSoup(sample_response.text, 'html.parser')

print(sample_response.text[:1000])

<!doctype html>
<html lang="en" class="no-js">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link href="https://fonts.googleapis.com/css?family=Open+Sans|Yellowtail|Montserrat:400,600" rel="stylesheet">
	<link rel="stylesheet" href="/css/reset.css"> <!-- CSS reset -->
	<link rel="stylesheet" href="/css/style.css"> <!-- Resource style -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

	<title>Details - Gene-Edited Animals for Agricultural Applications Database | ISAAA.org</title>
    <!-- GA4 added 11/14/2022 -->
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-FRYBT27V49"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-FRYBT27V49');
</script>


<!-- Facebook Pixel Code -->
<sc

In [ ]:
import time

df['Institute'] = ""
df['Editing_Method'] = ""
df['Delivery'] = ""
df['Foreign_DNA'] = ""
df['Regulatory_Process'] = ""

for idx, url in enumerate(df.loc[df['details_url'] != "", 'details_url']):
    print(f"Scraping details page {idx+1}/{len(df)}: {url}")
    
    resp = requests.get(url)
    soup = BeautifulSoup(resp.text, 'html.parser')
    
    def get_field_value(field_name):
        td_label = soup.find('td', text=lambda x: x and field_name in x)
        if td_label:
            td_value = td_label.find_next_sibling('td')
            if td_value:
                return td_value.get_text(strip=True)
        return ""
    
    df.loc[idx, 'Institute'] = get_field_value('Institute')
    df.loc[idx, 'Editing_Method'] = get_field_value('Editing Method')
    df.loc[idx, 'Delivery'] = get_field_value('Delivery')
    df.loc[idx, 'Foreign_DNA'] = get_field_value('Foreign DNA')
    df.loc[idx, 'Regulatory_Process'] = get_field_value('Undergone Regulatory Process')
    
    time.sleep(0.5)

df.head()

Scraping details page 1/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=89&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 2/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=151&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 3/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=196&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 4/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=127&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 5/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=32&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 6/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=207&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 7/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=195&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 8/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=145&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 9/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=79&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 10/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=55&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 11/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=90&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 12/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=165&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 13/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=7&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 14/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=65&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 15/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=110&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 16/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=5&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 17/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=186&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 18/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=121&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 19/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=129&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 20/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=133&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 21/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=182&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 22/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=99&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 23/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=43&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 24/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=46&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 25/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=91&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 26/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=81&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 27/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=27&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 28/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=209&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 29/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=100&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 30/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=6&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 31/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=208&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 32/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=80&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 33/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=48&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 34/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=72&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 35/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=57&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 36/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=141&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 37/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=156&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 38/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=159&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 39/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=176&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 40/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=183&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 41/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=88&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 42/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=187&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 43/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=112&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 44/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=170&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 45/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=201&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 46/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=36&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 47/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=52&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 48/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=205&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 49/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=98&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 50/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=82&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 51/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=76&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 52/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=102&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 53/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=103&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 54/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=106&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 55/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=108&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 56/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=154&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 57/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=166&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 58/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=175&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 59/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=177&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 60/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=118&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 61/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=124&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 62/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=130&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 63/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=87&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 64/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=199&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 65/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=202&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 66/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=184&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 67/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=109&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 68/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=45&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 69/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=51&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 70/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=94&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 71/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=69&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 72/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=111&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 73/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=114&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 74/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=180&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 75/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=74&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 76/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=4&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 77/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=58&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 78/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=63&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 79/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=70&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 80/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=29&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 81/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=142&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 82/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=104&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 83/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=75&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 84/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=150&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 85/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=152&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 86/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=164&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 87/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=71&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 88/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=25&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 89/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=8&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 90/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=194&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 91/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=193&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 92/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=198&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 93/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=204&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 94/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=140&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 95/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=155&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 96/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=146&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 97/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=73&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 98/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=62&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 99/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=67&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 100/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=149&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 101/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=157&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 102/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=158&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 103/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=163&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 104/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=197&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 105/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=128&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 106/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=143&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 107/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=28&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 108/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=139&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 109/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=78&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 110/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=147&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 111/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=93&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 112/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=56&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 113/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=60&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 114/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=1&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 115/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=105&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 116/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=173&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 117/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=188&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 118/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=191&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 119/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=3&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 120/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=122&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 121/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=125&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 122/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=126&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 123/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=38&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 124/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=96&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 125/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=148&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 126/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=181&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 127/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=206&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 128/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=107&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 129/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=113&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 130/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=117&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 131/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=169&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 132/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=119&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 133/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=120&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 134/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=134&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 135/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=136&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 136/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=138&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 137/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=144&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 138/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=97&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 139/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=85&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 140/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=30&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 141/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=167&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 142/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=200&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 143/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=153&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 144/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=59&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 145/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=64&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 146/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=115&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 147/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=172&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 148/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=101&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 149/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=132&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 150/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=68&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 151/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=116&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

Scraping details page 152/153: https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=203&RegProcess=0

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/1713350188.py:19: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

,year,country,animal_common,animal_scientific,gene,details_url,Institute,Editing_Method,Delivery,Foreign_DNA,Regulatory_Process
0,Year,Country of 1st Author,Species,,Genes,,Hendrix Genetics Research & Technology Service...,Other,The repair template carrying the marker gene f...,Yes,No
1,2023,Australia,Chicken\r\n (,Gallus gallus,Site directed integration for null-segregant t...,https://www.isaaa.org/animalbiotechdatabase/de...,Agricultural Technology Research InstituteXian...,Embryo edit,Directive microinjection of two gRNAs and Cas9...,No,No
2,,China,Pig\r\n (,Sus scrofa domesticus,CD163,https://www.isaaa.org/animalbiotechdatabase/de...,"Jilin University, ChangchunJilin ProvinceCN",Cloned cell line,The three plasmids were cotransfected into cel...,Yes,No
3,,China,Pig\r\n (,Sus scrofa domesticus,pAPN,https://www.isaaa.org/animalbiotechdatabase/de...,Jiangsu Provincial Engineering Research Center...,Embryo edit,,No,No
4,,China,Sheep\r\n (,Ovis aries,MSTN,https://www.isaaa.org/animalbiotechdatabase/de...,Southwest University400715 ChongqingCN,Embryo edit,Let-7-gRNA transgenic vector was microinjected...,Yes,No

In [6]:
df.to_csv("isaa_animalbiotech_full_details.csv", index=False)

print("Saved full dataset with details to 'isaa_animalbiotech_full_details.csv'")
print("Total rows:", len(df))

Saved full dataset with details to 'isaa_animalbiotech_full_details.csv'
Total rows: 153

In [ ]:
# now for ones that have, in fact, undergone regulatory processes

In [7]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://www.isaaa.org/animalbiotechdatabase/ngtlist/ngt/default.asp?NGTID=2&RegProcess=1"
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

# Find the main data table
table = soup.find('table')

# Extract all rows
rows = table.find_all('tr')

data = []

for row in rows:
    cells = row.find_all('td')
    if len(cells) < 5:
        continue
    
    year = cells[0].get_text(strip=True)
    country = cells[1].get_text(strip=True)
    
    # Split common and scientific names
    animal_common = cells[2].contents[0].strip() if cells[2].contents else ""
    animal_scientific = cells[2].em.get_text(strip=True) if cells[2].em else ""
    
    gene = cells[3].get_text(strip=True)
    details_url = "https://www.isaaa.org" + cells[4].a['href'] if cells[4].a else ""
    
    data.append({
        "year": year,
        "country": country,
        "animal_common": animal_common,
        "animal_scientific": animal_scientific,
        "gene": gene,
        "details_url": details_url
    })

df2 = pd.DataFrame(data)
print("Basic table scraped — rows found:", len(df2))
df2.head()

Basic table scraped — rows found: 21

,year,country,animal_common,animal_scientific,gene,details_url
0,Year,Country of Determination,Species,,Genes,
1,2026,Canada,Pig\r\n (,Sus scrofa domesticus,CD163,https://www.isaaa.org/animalbiotechdatabase/de...
2,2025,Argentina,Pig\r\n (,Sus scrofa domesticus,CD163,https://www.isaaa.org/animalbiotechdatabase/de...
3,,Dominican Republic,Pig\r\n (,Sus scrofa domesticus,CD163,https://www.isaaa.org/animalbiotechdatabase/de...
4,,Japan,Nile tilapia\r\n (,Oreochromis niloticus,MSTN,https://www.isaaa.org/animalbiotechdatabase/de...

In [8]:
df2['Institute'] = ""
df2['Editing_Method'] = ""
df2['Delivery'] = ""
df2['Foreign_DNA'] = ""
df2['Regulatory_Process'] = ""

In [9]:
import time

def get_field_value(soup, field_name):
    td_label = soup.find('td', text=lambda x: x and field_name in x)
    if td_label:
        td_val = td_label.find_next_sibling('td')
        if td_val:
            return td_val.get_text(strip=True)
    return ""

for idx, url in enumerate(df2.loc[df2['details_url'] != "", 'details_url']):
    print(f"({idx+1}/{len(df2)}) Fetching {url}")
    resp = requests.get(url)
    detail_soup = BeautifulSoup(resp.text, 'html.parser')
    
    df2.loc[idx, 'Institute'] = get_field_value(detail_soup, 'Institute')
    df2.loc[idx, 'Editing_Method'] = get_field_value(detail_soup, 'Editing Method')
    df2.loc[idx, 'Delivery'] = get_field_value(detail_soup, 'Delivery')
    df2.loc[idx, 'Foreign_DNA'] = get_field_value(detail_soup, 'Foreign DNA')
    df2.loc[idx, 'Regulatory_Process'] = get_field_value(detail_soup, 'Undergone Regulatory Process')
    
    time.sleep(0.4)  # polite delay

df2.head()

(1/21) Fetching https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=215&RegProcess=1

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

(2/21) Fetching https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=212&RegProcess=1

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

(3/21) Fetching https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=213&RegProcess=1

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

(4/21) Fetching https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=214&RegProcess=1

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

(5/21) Fetching https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=210&RegProcess=1

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

(6/21) Fetching https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=22&RegProcess=1

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

(7/21) Fetching https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=12&RegProcess=1

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

(8/21) Fetching https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=21&RegProcess=1

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

(9/21) Fetching https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=18&RegProcess=1

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

(10/21) Fetching https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=16&RegProcess=1

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

(11/21) Fetching https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=17&RegProcess=1

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

(12/21) Fetching https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=9&RegProcess=1

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

(13/21) Fetching https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=211&RegProcess=1

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

(14/21) Fetching https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=10&RegProcess=1

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

(15/21) Fetching https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=23&RegProcess=1

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

(16/21) Fetching https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=24&RegProcess=1

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

(17/21) Fetching https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=11&RegProcess=1

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

(18/21) Fetching https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=13&RegProcess=1

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

(19/21) Fetching https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=20&RegProcess=1

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

(20/21) Fetching https://www.isaaa.org/animalbiotechdatabase/details/default.asp?ABDEntryID=19&RegProcess=1

/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)
/var/folders/60/2gw19nzn43zdf99_4fqt2x6w0000gn/T/ipykernel_23433/3214513989.py:4: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  td_label = soup.find('td', text=lambda x: x and field_name in x)

,year,country,animal_common,animal_scientific,gene,details_url,Institute,Editing_Method,Delivery,Foreign_DNA,Regulatory_Process
0,Year,Country of Determination,Species,,Genes,,,Embryo edit,,No,Yes
1,2026,Canada,Pig\r\n (,Sus scrofa domesticus,CD163,https://www.isaaa.org/animalbiotechdatabase/de...,,Embryo edit,,No,Yes
2,2025,Argentina,Pig\r\n (,Sus scrofa domesticus,CD163,https://www.isaaa.org/animalbiotechdatabase/de...,,Embryo edit,,No,Yes
3,,Dominican Republic,Pig\r\n (,Sus scrofa domesticus,CD163,https://www.isaaa.org/animalbiotechdatabase/de...,,Embryo edit,,No,Yes
4,,Japan,Nile tilapia\r\n (,Oreochromis niloticus,MSTN,https://www.isaaa.org/animalbiotechdatabase/de...,,Embryo edit,,No,Yes

In [10]:
df2.to_csv("isaa_animalbiotech_regprocess1_full.csv", index=False)
print("Saved as 'isaa_animalbiotech_regprocess1_full.csv' (rows:", len(df2), ")")

Saved as 'isaa_animalbiotech_regprocess1_full.csv' (rows: 21 )